# Navigation Links

main:
  - name: Acerca
    url: under_construction
    weight: 10
  - name: Noticias
    url: post
    weight: 20
  - name: Equipo
    url: people
    weight: 30
  - name: Eventos
    url: under_construction
    weight: 40
  - name: Publicaciones
    url: publication
    weight: 50
  - name: Contacto
    url: contact
    weight: 60
